### ISSUE TITLE
Please restore `--nofetch` flag to support Yarn

### ISSUE THREAD

**Issue by kirillgroshkov** [apache/cordova-cli#303]
We're using Yarn and without `--nofetch` our `node_modules` folder gets screwed by npm (invoked by `cordova-fetch`). We would really really like `--nofetch` back to be able to work.

**Comment by raphinesse** [comment]
Actually, this *could* have been fixed by https://github.com/apache/cordova-fetch/pull/24. Could you please check if your problem persists when using a recent nightly build? `cordova@8.0.1-nightly.2018.8.26.9a2be3df` should work.

**Comment by kirillgroshkov** [comment]
Looking at the PR and description I don't believe it work (cause e.g we don't have plugins in `node_modules` at all, since we don't use `cordova-fetch`).

Also, I don't feel comfortable to test nightlies, cause something else can be broken.

But I'm ready to test when the next release is shipped! Will it be release of `cordova` (cli) package?

**Comment by raphinesse** [comment]
> Looking at the PR and description I don't believe it work (cause e.g we don't have plugins in node_modules at all, since we don't use `cordova-fetch`).

Well, then where does `yarn` install your dependencies if not in `node_modules`?

You should probably clarify your use case. Because I don't think `--no-fetch` will be coming back in its previous form. But maybe your use case can still be handled. What do you want to do and what do you want to happen? Step-by-step instructions help tremendously.

> Also, I don't feel comfortable to test nightlies, cause something else can be broken.

It won't set your machine on fire, I promise :wink:. But seriously, I am only asking you to test it, not to use it in production.

> But I'm ready to test when the next release is shipped! Will it be release of cordova (cli) package?

The change will be part of the next Cordova CLI major version. Testing it only after that has been released might be a little late. The earlier we know what you really need, the earlier we *can* start working on it :wink:

**Comment by kirillgroshkov** [comment]
Thanks for detailed comments!

Currently we use `cordova@7.1` because it has `--nofetch` working. It fetches plugins into `plugins` directory (not in `node_modules`).

What we would like to have:
- To be on the latest version of Cordova
- To keep using Yarn (and `yarn.lock`) as we do (and not use `npm` / `package-lock.json`)

Cordova 8 doesn't have `--nofetch`, so when we run e.g `cordova platform add android` it "screws" our `node_modules` folder, cause Yarn and npm are incompatible in a way they store files in `node_modules`.

Since I see the effort to help from your side - I'll do my best to test it with the nightly build as you suggested!

**Comment by kirillgroshkov** [comment]
I tried nightly, previously cleaned `platforms` and `plugins` folders, but kept `node_modules` and `yarn.lock` intact. Here's the result.

`cordova platform add android`

```
Using cordova-fetch for cordova-android@7.1.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.naturalcycles.cordova
	Name: Natural_Cycles
	Activity: MainActivity
	Android target: android-27
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.1.0
Android Studio project detected
Android Studio project detected
*** /Users/kirill/Idea/NCApp3/cordova-hooks/before_prepare.js started ***
Command failed: yarn ts-node -r tsconfig-paths/register ./src/scripts/addSourceMappingUrl.ts --dir /Users/kirill/Idea/NCApp3/www/build
module.js:549
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kirill/Idea/NCApp3/node_modules/ts-node/dist/bin.js:9:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
```

It broke on one of our cordova hooks, because previously it "screwed" `node_modules`, so package `minimist` disappeared (it's not even our dependency, it's some sub-dependency of something). It generated `package-lock.json` as a proof that it used `npm` underneath, and it's known that you cannot run `npm` when you have `node_modules` folder installed by Yarn.

So, problem is there.

**Comment by raphinesse** [comment]
@kirillgroshkov Thanks for testing! Could you please re-run your experiment using `--verbose` (i.e. `cordova platform add android --verbose`) and also share the output of running `cordova info` in your project root (always using the nightly). That would be great!

**Comment by dpogue** [comment]
To provide a bit of background here, there are several reasons that `--no-fetch` will not be coming back, but I *believe* what we want to accomplish should be compatible with Yarn.

The old installation code was unfortunately tied to npm2, which is several years old and relies on versions of dependencies with known security vulnerabilities. Because npm2 was installed as a dependency, running npm scripts within projects using Cordova would run with npm2 rather than the system npm. This was a frequent source of problems for users of Cordova, because npm2 and npm3 have different behaviour around peerDependencies.
The previous code was also doing custom behaviour that bypassed npm's caching helpers, didn't perform all the same verifications on the downloaded packages (which meant packages could get corrupt, and stick around), and was essentially us trying to poorly replicate a bunch of npm's behaviour. The code was unmaintainable and a source of continued bugs.

The way forward for Cordova is to have platforms and plugins listed in package.json and installed into node_modules. When you ask Cordova to install something, it will use npm to install it **if it is not already installed**.

From what I understand, this means it should be possible to make this work with Yarn, but you'll need to add the platforms to your package.json manually, and install them with Yarn.

For instance, with the following in your package.json:
```json
{
  "dependencies": {
    "cordova-android": "^7.1.0"
  },
  "cordova": {
    "platforms": [
      "android"
    ]
  }
}
```

After you run `yarn install`, you should be able to run `cordova prepare` (on the nightly build) to create the `platforms/android` folder without npm being invoked.

**Comment by kirillgroshkov** [comment]
@leandro-manifesto totally agree, cordova should do it's job and not try to do npm's (or yarn's or pnpm's) job.

**Comment by dpogue** [comment]
I would love to do that, but people need to be able to run commands like `cordova platform add` and `cordova plugin add`, and that needs to add the platform/plugin to package.json and install it into node_modules. We need to use npm to do that.

What we can do (and I'm working on this) is to not run any package management commands as part of `cordova prepare`. We should tell people to run npm/yarn/pnpm themselves and then look for what we need in node_modules, and warn if we can't find it.

**Comment by kirillgroshkov** [comment]
@dpogue 

1. Just an idea, maybe `cordova platform/plugin add` should just add lines to configuration file (`package.json`) and then user can just use his package manager (npm/yarn/pnpm) to get dependencies installed (running `npm i` / `yarn` / etc)?

> What we can do (and I'm working on this) is to not run any package management commands as part of cordova prepare. We should tell people to run npm/yarn/pnpm themselves and then look for what we need in node_modules, and warn if we can't find it.

Oh, that would be awesome, it'll solve the problem for so many people!

**Comment by paulsouche** [comment]
Hi,

Can't wait for this too ! But what about yarn workspaces and plug and play ? Dependencies won't always be local.

Thanks anyway for the great job

**Comment by marckassay** [comment]
An alternative to @dpogue recommendation, is installing and configuring spypkg so that npm will be mapped to yarn. See configuration [here](https://www.npmjs.com/package/spypkg#yarn-in-lieu-of-npm-configuration-example).

**Comment by kirillgroshkov** [comment]
Crazy that such complex solutions as spypkg are developed to address this issue:) Should indicate the need for native yarn support!

If Capacitor (https://capacitor.ionicframework.com/) will reach GA sooner - we'll probably switch to it instead of waiting for yarn support here...

**Comment by janpio** [comment]
@kirillgroshkov Cordova is open source. Feel free to submit a Pull Request.

**Comment by cmckni3** [comment]
Would the work need to be done in [cordova-lib](https://github.com/apache/cordova-lib). cordova-cli appears to be a wrapper to me.

**Comment by raphinesse** [comment]
The feature as requested here will most likely not be re-implemented. We are however aware of the fact that people want to use different package managers for various reasons. We plan to cater to these needs by doing less package management ourselves like @dpogue wrote in https://github.com/apache/cordova-cli/issues/303#issuecomment-429450550. However, this is a _huge_ task and we are seriously short on developers that have the time and knowledge to tackle it. Almost all work on Cordova is done by volunteers in their spare time.

**Comment by kirillgroshkov** [comment]
Sad, but I understand. We'll need to stay on Cordova 7.1 then and keep using `--nofetch`

**Comment by raphinesse** [comment]
@kirillgroshkov Did you test Cordova 9? `cordova-fetch` never should call `npm` if all your Cordova dependencies are already installed and all of them are referenced by version (i.e. from registry).

**Comment by kirillgroshkov** [comment]
I haven't tried Cordova 9 yet. How does `cordova-fetch` detect that "dependencies are already installed"? Right now we install to `plugins` folder (not to `node_modules`, due to reasons mentioned in this thread). If it tries to detect dependencies in `node_modules` and we install them with `yarn` - will `cordova-fetch` be able to detect that?

**Comment by raphinesse** [comment]
@kirillgroshkov Cordova will follow the standard module resolution rules of Node.js (details in https://github.com/apache/cordova-fetch/issues/43 and the PR linked therein), starting in your project root.

**Comment by kirillgroshkov** [comment]
> @kirillgroshkov Did you test Cordova 9? `cordova-fetch` never should call `npm` if all your Cordova dependencies are already installed and all of them are referenced by version (i.e. from registry).

Since when (which version of Cordova) is this logic in `cordova-fetch` applied? When we tried Cordova 7.1 and 8 - it *did* invoke `npm install` despite the fact that all plugins from `config.xml` were already installed in `node_modules`.

**Comment by raphinesse** [comment]
9

**Comment by kirillgroshkov** [comment]
> 9

Allright. Thanks for the info! I'll try 9 when I have time. If your description is correct - then it's great news and hopefully we can make it work with yarn (by preinstalling all dependencies with yarn and `cordova-fetch` should not interfere with package management in that case).

**Comment by raphinesse** [comment]
@kirillgroshkov Hope it works for you. When running whatever `cordova` commands you use, include the `--verbose` switch and watch out for [these log messages](https://github.com/apache/cordova-fetch/blob/master/index.js#L66). One of these pops up every time `cordova-fetch` installs a package (as opposed to using an already installed one).

**Comment by cmdickson** [comment]
> @kirillgroshkov Did you test Cordova 9? cordova-fetch never should call npm if all your Cordova dependencies are already installed and all of them are referenced by version (i.e. from registry).

So, this would exclude any local plugins?  The behaviour I am seeing is that `npm` is always invoked for plugins in `package.json` that use `file:...`

**Comment by raphinesse** [comment]
@cmdickson yes, we always need to invoke `npm` for local plugins.

**Comment by vzts** [comment]
Just verified that cordova v9.0.0's `cordova prepare` under pre-`yarn install` environment do not trigger cordova-fetch. It works nicely with yarn. Thanks for the guidance @raphinesse.

**Comment by QuentinFarizon** [comment]
@vzts @raphinesse I can confirm that npm install is not called when pre-yarn installed environment

BUT npm install is called when a cordova plugin has been added using `yarn add` with a git repository instead of the registry name (screwing node_modules as describes in this issue).
Ex : `yarn add git+https://github.com/videmort/cordova-plugin-referrer.git`
Vs standard `yarn add cordova-plugin-referrer`

This is a normal way to install dependencies, and useful when installing forks of cordova plugins. It make it impossible to have yarn + plugins referrenced by git urls

Please either re-add --nofetch, or make it use yarn if configured as such, or just check by looking in node_modules/cordova-plugin-referrer instead of a more complicated way (which fails here)

**Comment by QuentinFarizon** [comment]
I have worked around this issue in a funny way : by running a hook that restores node_modules after cordova has finished messing with it.

In config.xml :
```
    <hook src="hooks/before_build/run_yarn.js" type="before_build" />
```

hooks/before_build/run_yarn.js :
```
#!/usr/bin/env node

var exec = require('child_process').execSync;

module.exports = function(context) {
  exec('rm package-lock.json || echo "No package-lock.json to remove"');
  exec('yarn');
};
```
