### ISSUE TITLE
Can't restore plugins after cloning project from repo

### ISSUE THREAD

**Issue by drsgomes** [apache/cordova-cli#400]
Hi, I'm having problems to restore my plugins from a private project in github after updating from cordova 6.5 to 8.1.2. Basically I have a `.gitignore` for the folders `plugins/` and `platforms/` as they are generated and contain duplicated data. I've used in that way till now without issues. I had to upgrade my project, now I can't use this approach anymore. When I try to restore the project I get errors like the one below.

I tried to downgrade and use a previous version of cordova, like 7, but still not working.

I'm using ionic here, but I can get same error when I try directly with cordova commands.

Another note is that this is not happening with plugins in npm public repo, the ones I add with a name, just with the ones I have to add with a git url.

Thanks

**Error:**
Discovered plugin "cordova-plugin-telerik-imagepicker" in config.xml. Adding it to the project
Failed to restore plugin "cordova-plugin-telerik-imagepicker" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/Telerik-Verified-Plugins/ImagePicker.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**How to reproduce:**
```
ionic version: 4.10.2
cordova version: 8.1.2
```

These steps are used to create a project from the scratch
```
ionic start ionic-issue-dependencies blank --type=ionic-angular
cd ionic-issue-dependencies
ionic cordova platform add android
ionic cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker.git
```

This would be done before saving to github (actually done via .gitignore)
```
rm -rf plugins
rm -rf platforms
rm -rf node_modules
```

This is normally done after a fresh clone of the repo
```
npm install
ionic cordova platform add android
```

Logs:
```
$ ionic cordova platform add android
> cordova platform add android --save
Using cordova-fetch for cordova-android@7.1.4
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.ionic.starter
	Name: MyApp
	Activity: MainActivity
	Android target: android-27
Android project created with cordova-android@7.1.4
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for android
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for android
Adding cordova-plugin-ionic-keyboard to package.json
Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
Discovered plugin "cordova-plugin-telerik-imagepicker" in config.xml. Adding it to the project
Failed to restore plugin "cordova-plugin-telerik-imagepicker" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/Telerik-Verified-Plugins/ImagePicker.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
--save flag or autosave detected
Saving android@~7.1.4 into config.xml file ...
[ERROR] An error occurred while running subprocess cordova.

        
        cordova platform add android --save exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

**Comment by drsgomes** [comment]
> Just an idea: Does it work if you install the plugin via `cordova plugin add cordova-plugin-telerik-imagepicker` or `https://github.com/Telerik-Verified-Plugins/ImagePicker`?

This plugin as just an example, I have about 4-8 plugins using git url, now on a private repo. Basically all plugins I install with `cordova plugin add plugin-id` works well. The ones I install with `cordova plugin add https://github.com/...` don't. But that issues happens only I clone the project and want to restore the app state. In that case, there is no node_modules, plugins or platforms folders.

**Comment by janpio** [comment]
Ok, missed that sentence in your initial issue description.

**Comment by dpogue** [comment]
> I have about 4-8 plugins using git url, now on a private repo.

Do those private repos contain a package.json file?

Also, I've found a slightly better way to do it with GitHub repos is to use a format like `github:Telerik-Verified-Plugins/ImagePicker` instead of a URL

**Comment by drsgomes** [comment]
> Do those private repos contain a package.json file?


Yeap, all of them. The one I used in this example has one too. `https://github.com/Telerik-Verified-Plugins/ImagePicker/blob/master/package.json`

**Comment by drsgomes** [comment]
The only way I could get things working was to:
- remove all plugins from config.xml
- remove all plugins from package.json (from dependencies & plugins sections)
- run a script for each plugin with the command line to add: e.g: ` ionic cordova plugin add http://...`

**Comment by drsgomes** [comment]
I found this related issue [here](https://github.com/apache/cordova-cli/issues/387). That solved my problem for now, it's a workaround, but at least it's working. My approach was to call on `postinstall` a custom script. This script reads `config.xml` and search for all plugins with `git` or `http` in the spec field. These are the plugins failing. Then I delete them from `node_modules`. Working 👍

**Comment by drsgomes** [comment]
Just some update, it's actually not working. For some reason, the method I used above didn't work. The build process went fine, but when I tried to run it on iPhone and Android the app got stuck in the splash screen. I noticed some error related to the js/ts files. For now I think the only workaround for me is to not add the private plugins to config.xml & package.json. Then, I add then via a script.

**Comment by raphinesse** [comment]
I just successfully tested the following sequence using `cordova@9.0.0` with `cordova-lib@9.0.1`:
```
npm i -g cordova@latest
cd $(mktemp -d)
cordova create test-app && cd test-app
cordova platform add browser
cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker.git
rm -rf plugins/ platforms/ node_modules/
npm i
cordova platform add browser

```
Closing this issue as it seems to be resolved in latest Cordova. If it is not resolved for you, please report back to us here.

**Comment by 8bhsolutions** [comment]
I am having the same issue. I'm on cordova@9.0.0 with cordova-lib@9.0.1.

Further investigation, it's seems that cordova prepare expects the plugins to be available on npmjs.

The retest passes because Telerik-Verified-Plugins/ImagePicker.git was published to npmjs in March
https://www.npmjs.com/package/cordova-plugin-telerik-imagepicker

Below is a debug log from npm:
`
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'view',
1 verbose cli   'com.eightbhs.power-button-listener',
1 verbose cli   '--json' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 silly mapToRegistry name com.eightbhs.power-button-listener
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data { type: 'tag',
7 silly mapToRegistry   registry: true,
7 silly mapToRegistry   where: undefined,
7 silly mapToRegistry   raw: 'com.eightbhs.power-button-listener',
7 silly mapToRegistry   name: 'com.eightbhs.power-button-listener',
7 silly mapToRegistry   escapedName: 'com.eightbhs.power-button-listener',
7 silly mapToRegistry   scope: undefined,
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   saveSpec: null,
7 silly mapToRegistry   fetchSpec: 'latest',
7 silly mapToRegistry   gitRange: undefined,
7 silly mapToRegistry   gitCommittish: undefined,
7 silly mapToRegistry   hosted: undefined }
8 silly mapToRegistry uri https://registry.npmjs.org/com.eightbhs.power-button-listener
9 verbose request uri https://registry.npmjs.org/com.eightbhs.power-button-listener
10 verbose request no auth needed
11 info attempt registry request try #1 at 22:58:34
12 verbose request id 80ae7fe4b5301b5d
13 http request GET https://registry.npmjs.org/com.eightbhs.power-button-listener
14 http 404 https://registry.npmjs.org/com.eightbhs.power-button-listener
15 verbose headers { date: 'Wed, 19 Jun 2019 12:58:35 GMT',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'content-length': '21',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'set-cookie':
15 verbose headers    [ '__cfduid=db81579bd261b025f31e36d44a3a0dac71560949114; expires=Thu, 18-Jun-20 12:58:34 GMT; path=/; domain=.npmjs.org; HttpOnly' ],
15 verbose headers   'cf-cache-status': 'MISS',
15 verbose headers   'cache-control': 'max-age=300',
15 verbose headers   'cf-ray': '4e95acde1f0c1d4e-MEL',
15 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
15 verbose headers   vary: 'accept-encoding, accept',
15 verbose headers   server: 'cloudflare' }
16 verbose stack Error: Not found : com.eightbhs.power-button-listener
16 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:329:12)
16 verbose stack     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:317:14)
16 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:14)
16 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:185:22)
16 verbose stack     at emitTwo (events.js:126:13)
16 verbose stack     at Request.emit (events.js:214:7)
16 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1161:10)
16 verbose stack     at emitOne (events.js:116:13)
16 verbose stack     at Request.emit (events.js:211:7)
16 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1083:12)
16 verbose stack     at Object.onceWrapper (events.js:313:30)
16 verbose stack     at emitNone (events.js:111:20)
16 verbose stack     at IncomingMessage.emit (events.js:208:7)
16 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
16 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
16 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
17 verbose statusCode 404
18 verbose pkgid com.eightbhs.power-button-listener
19 verbose cwd DELETE
20 verbose Windows_NT 10.0.17134
21 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view" "com.eightbhs.power-button-listener" "--json"
22 verbose node v8.12.0
23 verbose npm  v6.4.1
24 error code E404
25 error 404 Not found : com.eightbhs.power-button-listener
26 error 404
27 error 404 'com.eightbhs.power-button-listener' is not in the npm registry.
28 error 404 You should bug the author to publish it (or use the name yourself!)
29 error 404 Note that you can also install from a
30 error 404 tarball, folder, http url, or git url.
31 verbose exit [ 1, true ]
`

package.json file for this plugin:
https://github.com/8bhsolutions/cordova-plugin-power-button-listener/blob/master/package.json

**Comment by 8bhsolutions** [comment]
Discussion on this same problem

https://stackoverflow.com/questions/50749953/cordova-8-how-do-you-add-plugins-that-are-not-in-npm-registry

**Comment by gzbakku** [comment]
anybody having this problem just delete node_modules, plugins and platform folder from your base  cordova directory and run -  `npm i` then run - `cordova platform add android` or ios

**Comment by rajohns08** [comment]
I saw this issue, but it started working for me after I downgraded to node 14.18.2?
