### ISSUE TITLE
[9.0.0] requireCordovaModule — 

### ISSUE THREAD

**Issue by artuska** [apache/cordova-cli#416]
Cordova 9.0.0 throws an error:

```
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

There are thousands of Cordova plugins which is still using `requireCordovaModule` in their code, e.g.:

```
var deferred = new context.requireCordovaModule('q').defer();
```

So, is there some workaround about it? Or i just have to switch back to 8.x.x version?

**Comment by dpogue** [comment]
This was intentionally removed as part of the major version bump because we found that plugins were breaking when Cordova changed its internal dependencies, due to the use of `requireCordovaModule`. (i.e., we're in the process of looking to remove `q` from our dependencies, which would break any plugin that used `requireCordovaModule('q')`)

Plugins should be updated to list their dependencies in package.json and use normal `require` to load them. Yes, this likely means a bunch of plugins need to be updated, which is why it was done in a major version bump.
