### ISSUE TITLE
Feature request: Build time cordova plugins loading/bundling/concatanation/minification

### ISSUE THREAD

**Issue by guylando** [apache/cordova-cli#417]
The goal is to improve cordova app loading time by bundling all cordova plugins js files into one file instead of cordova.js loading cordova_plugins.js which in turn loads 30+ js files of different plugins. 

Saw there used to be browserify flag for that which was now removed.
Preferably to be able to do that using webpack which is the most popular bundler.

**Comment by dpogue** [comment]
This is what the browserify flag was previously intended to do, but we found it made a negligible impact on load times (30-50 ms improvement with 50 plugins) since all the plugin JS files are typically loaded from the device filesystem.

Additionally, the browserify (or other bundler) code was incompatible with some plugins (such as the WKWebView plugin for iOS, which needs to replace the exec bridge at runtime) and added significant maintenance complexity to all levels of the Cordova tooling.

At this point, I don't think we're interested in pursuing bundling due to the maintenance cost and the minimal impact.

**Comment by miguelperez** [comment]
Hi, Is there a way to bundle files? I have a an app that is working this way, loading the JS from a remote server. But this file needs to be bundled with all the plugins.
