### ISSUE TITLE
(feature) Set the app-id, name and version by CLI or build.json.

### ISSUE THREAD

**Issue by Domvel** [apache/cordova-cli#463]
# Feature Request

## Motivation Behind Feature
I have one config.xml in a multi-app workspace and want to change the id dynamically before build. I could to this by e.g. a custom node-script to string replace it in the config.xml. But I prefer a more official way.

## Feature Description
Is it already possible to set the app-id, name and version dynamically by CLI or a separated config file like build.json? I only want one config.xml and have only one package.json. But multiple apps in an Angular workspace. All works fine. But I want to set the app-id, name, version, etc. by the CLI or a separated lightwight config json like build.json. I have no idea what the build.json is. But it looks like that this is for app signing only. The build json should be progressive. Means if I only set the app-id, the other values like name, version, etc. should come the default or from config.xml.

I think about CLI command: 

```text
cordova build android --release --config.id="com.foo.bar" --config.name="Foobar" --config.version="1.2.3"
```

Same for `run` command.

Or in a separated progressive config / build.json:

```json
{
  "config": {
    "id": "com.foo.bar",
    "name": "Foobar",
    "version": "1.2.3"
  }
}
```

## Alternatives or Workarounds
I have to write a script in Node Js to replace the string in config.xml. Or change the id, etc. manually. In best case I do not want to modificate the config.xml.

**Comment by dpogue** [comment]
I doubt this is anything that Cordova will add support to the CLI for, because it has a bunch of complicating effects when you try to do something like running `prepare` with one set of values and then `build` with another set. There are multiple parts of the package that would need updating, in some cases including file paths.

However, I have a similar use case at work for making different builds for staging, qa, and production environments, and I wrote a small tool to set these values from environment variables: [seymour](https://npm.im/seymour). Not sure it does exactly what you're looking for (since it does modify config.xml) but it sounds pretty close, and I'd be happy to see if it makes sense to add support for what you need.
