### ISSUE TITLE
cordova diagnostic command

### ISSUE THREAD

**Issue by breautek** [apache/cordova-cli#526]
# Feature Request

## Motivation Behind Feature

A single command that collects most the information (and maybe more) that our github issue template requests.

## Feature Description

The collected information should include:

- OS platform & Version
- XCode version (if on mac)
- Android Studio version & installed android sdks
- Installed java version
- NodeJS & NPM version
- Cordova version
- Installed cordova platforms & their versions
- Installed cordova plugins & their versions
- The NPM dependency tree via `npm ls` (see https://github.com/apache/cordova-android/issues/1027#issuecomment-677762390)
- Any other environment information that might be relevant for each platform. This isn't necessary a complete list.

Obviously this won't cover everything that is requested in our issue template, such as:

- The problem they are experiencing
- The actual result they are expected
- What mobile devices they are using

But we'll still would then be able to request/tell the user to run `cordova diagnostic` which will print out or perhaps write to a file. Of course not everyone will bother, but this command will be far more easier than telling the user to run variety of different commands to get this information that we request.

**Comment by raphinesse** [comment]
I think it's debatable if the Java version is actually needed. After all we just re-assured ourselves that nothing except Java 8 will work anyway :sweat_smile:. It still would be nice to have of course. The recent refactoring in #510 prepared the platform info API, where platform specific environment information should be collected by the platform and provided to CLI in a generic structured format. Since cordova-android is the only part of Cordova that uses Java, Java version information should be provided by cordova-android's upcoming info API.

Regarding the node modules dependency tree: running `npm ls` takes very long usually, so I would prefer to avoid running it as part of `cordova info`. If needed, users can easily provide that information separately.

**Comment by breautek** [comment]
> I think it's debatable if the Java version is actually needed. After all we just re-assured ourselves that nothing except Java 8 will work anyway sweat_smile.

Yeah, but I mean, if it helps us pinpoint an environment flaw, I think it's still good to include.

> Regarding the node modules dependency tree: running npm ls takes very long usually, so I would prefer to avoid running it as part of cordova info. If needed, users can easily provide that information separately.

Perhaps. I just learned about the `npm ls` command myself. Just have to I guess tell people to either try clearing their `package-lock.json` / `node_modules` tree and reinstalling to ensure all their dependencies are up to date, especially when they have weird issues that aren't reproducible.

> Since cordova-android is the only part of Cordova that uses Java, Java version information should be provided by cordova-android's upcoming API method getEnvironmentInfo.

Agreed. And I think our consensus is the only thing that should be added is Java, so perhaps this issue should be closed and a new issue should be created in `cordova-android`?

**Comment by raphinesse** [comment]
> Agreed. And I think our consensus is the only thing that should be added is Java, so perhaps this issue should be closed and a new issue should be created in `cordova-android`?

If it's OK with you to drop the `npm ls` requirement then that would probably be the best course of action.
