### ISSUE TITLE
bug: macOS 12 monterey is not supported

### ISSUE THREAD

**Issue by eun-choi** [apache/cordova-cli#566]
# Bug Report

### What is expected to happen?

Build should also succeed on macOS 12(monterey).

### What does actually happen?

Build fails on macOS 12.0.1

## Information

cordova 10.0.0 uses macos-release 2.4.1 version in package-lock.json

In order to have no problems on macOS 12, macos-release version 2.5.0 is required.

### Environment, Platform, Device

Occurs with macos 12.0.1 and cordova 10.0.0

### Version information

Cordova: cordova 10.0.0, cordova-ios 6.2.0
Other Frameworks: @ionic/cli 6.18.0, macos 12.0.1, xcode 13.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by arturvt** [comment]
I forked and updated the required libs to make it work. I can send a PR if it's allowed. 
The issue is with  "os-name" lib. It should be updated to "^5.0.0".

I updated the libs related below, but it didn't update the lib we want, so I added as dependency into main package.json and it worked.

Here's the solution for unblocking you:
 
1. Clone the cli project2
2. Update those libs:
-  "cordova-lib": "^10.1.0",
- "insight": "^0.11.1",
- "systeminformation": "^5.9.9",
- "os-name": "^5.0.0",
3. run npm link cordova

**Comment by erisu** [comment]
Reinstall Cordova CLI.

```
npm uninstall -g cordova
npm install -g cordova
```

**Comment by eun-choi** [comment]
Before re-install:
```
cordova@10.0.0 /usr/local/lib/node_modules/cordova
└─┬ insight@0.10.3
  └─┬ os-name@3.1.0
    └── macos-release@2.4.1 

> cordova build ios
/usr/local/lib/node_modules/cordova/node_modules/macos-release/index.js:27
const [name, version] = nameMap.get(release);

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```


After re-install:
```
cordova@10.0.0 /usr/local/lib/node_modules/cordova
└─┬ insight@0.10.3
  └─┬ os-name@3.1.0
    └── macos-release@2.5.0 
```


This problem was solved by reinstalling.
However, if you upgrade macOS 12 with it already cordova 10 installed,
I suspect others will have the same problem.
(Because, it's been over a year since the cordova 10.0.0 version was released.)

**Comment by theblang** [comment]
For posterity, [here's the issue](https://github.com/sindresorhus/macos-release/issues/8) from the dependency repository.

**Comment by purplecabbage** [comment]
This is happening again with Ventura ... we need a future proof fix

**Comment by breautek** [comment]
> This is happening again with Ventura ... we need a future proof fix

Probably just get rid of `insight` package. We use it to display the "consumer" name of the Mac version instead of the Darwin version.

But unfortunately the underlying package can't see in the future nor do they gracefully handle unknown Darwin versions. Instead we can just use the NodeJS APIs (`OS.platform()` / `OS.release()` / `OS.version()`). Platform will provide `darwin` on macs, and either `release()` or `version()` will provide the version. `OS.version()` might be pretty much a direct replacement since it returns `"Windows 10 Pro"` rather than the actual OS version. (`release()` appears to return the actual version, e.g: `10.0.19045`
