### ISSUE TITLE
Cordova has dependencies which use deprecated libraries

### ISSUE THREAD

**Issue by master-bob** [apache/cordova-cli#610]
# Bug Report

## Problem

Installing Cordova comes with the following warnings:
```shell
# npm install -g cordova
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
```

### What is expected to happen?

I don't expect to get these warnings.

### What does actually happen?

I get warnings. The uuid warning is concerning.

### Version information
In an Ubuntu 20.04 container:
```shell
root@1483509730c2:/project# npm list -g
/usr/lib
├── bower@1.8.14
├── cordova@11.1.0
├── corepack@0.15.3
└── npm@9.5.0

root@1483509730c2:/project# node --version
v18.15.0
```

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
These come via `pacote` which is used by `cordova-fetch` to handle the npm installing of plugins and platforms.

The next version will update to a newer version of pacote which resolves most of these warnings.

**Comment by breautek** [comment]
> These come via `pacote` which is used by `cordova-fetch` to handle the npm installing of plugins and platforms.
> 
> The next version will update to a newer version of pacote which resolves most of these warnings.

This is true, however most of these warnings comes from the `request` package itself. Cordova has `request` currently through 2 dependencies, one is `pacote` via `cordova-fetch`, the other is via `insight`. The upcoming release of `cordova-fetch` does use an updated `pacote` which doesn't depend on `request` anymore, however `insight` still does and afaik `insight` is also no longer maintained (or it has moved to ESM so we cannot update easily cause it will require converting all of the cordova cli to esm, I kinda forget the case with `insight` but I recall looking into it awhile back).

`har-validator` is included because of `request`:

```
cordova@11.1.1-dev /development/cordova/coho/cordova-cli
└─┬ insight@0.11.1
  └─┬ request@2.88.2
    └── har-validator@5.1.5
```

`uuid@3` is being included because of `request`:

```
cordova@11.1.1-dev /development/cordova/coho/cordova-cli
├─┬ insight@0.11.1
│ ├─┬ request@2.88.2
│ │ └── uuid@3.4.0
```


`stringify-package` is included via `cordova-lib` (which seems to be still the case in current master):

```
cordova@11.1.1-dev /development/cordova/coho/cordova-cli
└─┬ cordova-lib@11.1.0
  └── stringify-package@1.0.1
```

`@npmcli/move-file` is being included via `pacote`:

```
cordova@11.1.1-dev /development/cordova/coho/cordova-cli
└─┬ cordova-create@4.1.0
  └─┬ cordova-fetch@3.1.0
    └─┬ pacote@11.3.5
      └─┬ cacache@15.3.0
        └── @npmcli/move-file@1.1.2
```

The `pacote` update addresses this, but current dev of cordova-fetch still has `@npmcli/move-file` via other `@npmcli` dependencies.

Lastly, `request` is included because of `pacote` (resolved in cordova-fetch master/v4.0.0) and via `insight`:

```
cordova@11.1.1-dev /development/cordova/coho/cordova-cli
├─┬ cordova-create@4.1.0
│ └─┬ cordova-fetch@3.1.0
│   └─┬ pacote@11.3.5
│     └─┬ @npmcli/run-script@1.8.6
│       └─┬ node-gyp@7.1.2
│         └── request@2.88.2 deduped
└─┬ insight@0.11.1
  └── request@2.88.2
```

**Comment by erisu** [comment]
Deprecated dependencies are just warnings and nothing to be concerned 
with.

We regularly update the package-lock.json to remove npm audit warnings when they appear, but the package-lock.json is also a Cordova development-only file. 

It is usually not an issue for end-users who uses Cordova since `npm install` does not have the package-lock.json file.

Most of the deprecated warnings will be removed in the next release. No all of them will be removed.

I am closing this ticket as it is not an issue.

**Comment by plasticlobster** [comment]
The `insight` dependency that may have been "just warnings" back in May now has a CVE attached to it, as the `request` package is no longer supported by the maintainer and will not be updated to patch its associated security issue.
CVE-2023-28155

While the pacote dependency cleanup in Cordova 12.0.0 does address one path of requiring `request`, the other path through `insight` is still very much an issue.

`insight` also seems to be a dead project with no updates since 2021.

I have no delved into why Cordova needs `insight`, but it seems like now might be a good time to strip that dependency.
