### ISSUE TITLE
Cordova-cli on MacOS Ventura?

### ISSUE THREAD

**Issue by bonjourjoel** [apache/cordova-cli#626]
# Bug Report

## Problem

Hey!

I wish I could use cordova also on **MacOS Ventura**. It doesn't work. The basic commands like `cordova platform add` and `cordova plugin add` don't work.

I don't know if i did something wrong in my setup, or if it's not supported. I have read all the documentation i could find on this topic, of which I couldn't find any.

Is it supported or not? Did I do something wrong? Is the answer already written somewhere and I wasn't able to find it?

### What does actually happen?

This is an example of the problem. This is an interactive session immediately after installing everything like cordova, xcode-select, ios-deploy, cocoapods, etc.

**% cordova create cordovatest**
> Creating a new cordova project.

**% cd cordovatest**

**% ls**
> config.xml	package.json	www

**% cordova platform add browser**
> Using cordova-fetch for cordova-browser
> Failed to fetch platform cordova-browser
> Probably this is either a connection problem, or platform spec is incorrect.
> Check your connection and platform name/version/URL.
> CordovaError: Error: Command failed with exit code 1: npm install cordova-browser --save-dev
> npm ERR! code EEXIST
> npm ERR! syscall mkdir
> npm ERR! path /Users/joel/.npm/_cacache/content-v2/sha512/e9/8a
> npm ERR! errno EEXIST
> npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/shelljs: EACCES: permission denied, mkdir '/Users/joel/.npm/_cacache/content-v2/sha512/e9/8a'
> npm ERR! File exists: /Users/joel/.npm/_cacache/content-v2/sha512/e9/8a
> npm ERR! Remove the existing file and try again, or run npm
> npm ERR! with --force to overwrite files recklessly.
> 
> npm ERR! A complete log of this run can be found in: /Users/joel/.npm/_logs/2023-09-03T06_02_24_559Z-debug-0.log

**% rm -rf /Users/joel/.npm/_cacache/content-v2/sha512/e9/8a**

**% cordova platform add browser**

> Using cordova-fetch for cordova-browser
> Failed to fetch platform cordova-browser
> Probably this is either a connection problem, or platform spec is incorrect.
> Check your connection and platform name/version/URL.
> CordovaError: Error: Command failed with exit code 1: npm install cordova-browser --save-dev
> npm ERR! code EEXIST
> npm ERR! syscall mkdir
> npm ERR! path /Users/joel/.npm/_cacache/content-v2/sha512/e9/8a
> npm ERR! errno EEXIST
> npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/shelljs: EACCES: permission denied, mkdir '/Users/joel/.npm/_cacache/content-v2/sha512/e9/8a'
> npm ERR! File exists: /Users/joel/.npm/_cacache/content-v2/sha512/e9/8a
> npm ERR! Remove the existing file and try again, or run npm
> npm ERR! with --force to overwrite files recklessly.
> 
> npm ERR! A complete log of this run can be found in: /Users/joel/.npm/_logs/2023-09-03T06_02_59_615Z-debug-0.log

**% sudo cordova platform add browser**
> Using cordova-fetch for cordova-browser
> ^C                                                                _[ctrl-c because it hanged.]_

**% sudo npm cache clean --force**
> npm WARN using --force Recommended protections disabled.

**% sudo cordova platform add browser**
> Using cordova-fetch for cordova-browser
> Adding browser project... _[it hangs here... but it finally responds]_
> Could not load API for browser project /Volumes/dev/cordovatest/node_modules/cordova-browser

**% ls -l node_modules/cordova-browser** 
> total 218
> -rwx------  1 joel  staff   1374 Sep  3 08:10 CONTRIBUTING.md
> -rwx------  1 joel  staff  17024 Sep  3 08:07 LICENSE
> -rwx------  1 joel  staff    168 Sep  3 08:07 NOTICE
> -rwx------  1 joel  staff   1621 Sep  3 08:10 README.md
> -rwx------  1 joel  staff   8212 Sep  3 08:10 RELEASENOTES.md
> -rwx------  1 joel  staff      6 Sep  3 08:07 VERSION
> drwx------  1 joel  staff  16384 Sep  3 08:09 bin
> drwx------  1 joel  staff  16384 Sep  3 08:10 cordova-js-src
> drwx------  1 joel  staff  16384 Sep  3 08:09 cordova-lib
> -rwx------  1 joel  staff   1033 Sep  3 08:10 package.json
> drwx------  1 joel  staff  16384 Sep  3 08:10 spec

### Version information

MacOs Ventura 13.5.1 (22G90)
Cordova 12.0.0 (cordova-lib@12.0.1)
NodeJs v18.17.1
Npm 9.6.7
Xcode Version 14.3.1 (14E300c)
xcode-select version 2397
Homebrew 4.1.7
gem version 3.0.3.1
pod version 1.12.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Ive been on MacOS Ventura 13.5 just fine.

Based on the output, it's NPM failing due to permission issues. This can be caused by mixing usages of `sudo`. Once you use `sudo` you'll be installing things under your root account, which will be a source of permission issues that might not be completely obvious until you try to run commands later.

The good news is, it appears that it appears that your NPM is configured to store the npm cache files under your user HOME directory, so `sudo` should not be required, but first you probably need to fix your environment.

### Step 1 - Nuking the NPM Cache

Delete the NPM cache (which you've already tried, but you should do so again since it appears you used `sudo` again afterwards with NPM (via `sudo cordova platform add ....`)

` sudo npm cache clean --force`

Note we are using `sudo` here just in case if there are any files/directories that is owned by root. You verify if this worked by checking if `~/.npm/_cacache` directory exists. It should have been deleted after running the cache clean command.

### Step 2 - Nuking node_modules

Now, delete your node_modules, since you've been exiting out npm install commands, it may also be in a bad state.

`sudo rm -rf node_modules/`

I'm using `sudo` again here just in case there are directories/files owned by root in your node_modules foler.

Based on your `ls` output, it doesn't look like NPM created a `package-lock.json` file, but if there is one, delete it too.

### Step 3 - Attempting to reinstall

From this point on, NPM will be **SLOW**, because you have no cache. NodeJS modules are notoriously bad for having tiny little packages and for each one will now require a network hit, and will requiring download and unpacking the contents. So patience will be needed. If you like, you can use `--verbose` flag on any of `cordova` commands to see more output, which may give you more confidence that stuff is actually happening (and in likeliness, stuff will wait on NPM to complete it's work). Once NPM builds up it's cache from stuff that you commonly install it will speed up since it can install packages from cache rather than from the network.

More importantly, from here on out, `sudo` is not to be used. If you use `sudo` again with any NPM or cordova commands, you may start running into permission issues again.

Additionally, I don't trust your globally installed packages and additional work will be needed if you have `sudo` installed any global packages. Therefore, for the time being I'm going to instruct you to install local (project) copies of Cordova, which is actually kind of better practice to begin with.

So first install cordova (without `sudo`!):

`npm install cordova`

Now, to use your local cordova install (instead of global) you can use the `npx` command prefix, which instructs NPM to look for the cordova exectable in your local node_modules.

`npx cordova platform add browser --verbose`

All of cordova documentation assumes you have a global install of `cordova`, so with the local install, `npx` command prefix will be required to run cordova, otherwise you may run your global cordova install.

Let me know if this helps.

**Comment by bonjourjoel** [comment]
Thank you. You're very helpful.
